blank_issues_enabled: true
contact_links:
  - name: CamClops Discussions
    url: https://github.com/Nutball-Labs/CamClops/discussions
    about: General questions, feature ideas, and community support
